version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/code/staticfiles
      - ./core:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/code/staticfiles
      - ./core:/app
    depends_on:
      - django

  bot:
    container_name: bot
    command: python3 bot/app.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  static:
