version: '3'

services:
  django:
    build: .
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./path/to/your/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django

  bot:
    container_name: bot
    command: python3 bot/app.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile

volumes:
  static:
