# Generated by Django 4.2.7 on 2023-11-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0006_remove_videoapp_comment_videoapp_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoapp",
            name="marked_view",
            field=models.BooleanField(default=False),
        ),
    ]
